# Generated by Django 2.0.1 on 2018-01-28 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(db_column='id')),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(db_column='firstName', max_length=255)),
                ('last_name', models.CharField(db_column='lastName', max_length=255)),
                ('is_staff', models.IntegerField(db_column='isAdmin')),
                ('limbopassword', models.CharField(db_column='limboPassword', max_length=128)),
                ('phone', models.CharField(max_length=31)),
                ('emergencyname', models.CharField(db_column='emergencyName', max_length=255)),
                ('emergencyphone', models.CharField(db_column='emergencyPhone', max_length=31)),
                ('dob', models.CharField(max_length=10)),
                ('profilepic', models.CharField(db_column='profilePic', max_length=512)),
                ('canroom', models.IntegerField(db_column='canRoom')),
                ('newuser', models.IntegerField(db_column='newUser')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='Canroompreauth',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'canRoomPreAuth',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('when', models.CharField(max_length=10)),
                ('housecharge', models.IntegerField(db_column='houseCharge')),
                ('notes', models.CharField(max_length=4095)),
            ],
            options={
                'db_table': 'tab',
            },
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('zip', models.IntegerField()),
                ('extra', models.SmallIntegerField()),
                ('shirt', models.IntegerField()),
                ('badgename', models.CharField(db_column='badgeName', max_length=255)),
                ('spam', models.IntegerField()),
                ('badgeadded', models.IntegerField(db_column='badgeAdded')),
                ('badgedata', models.CharField(db_column='badgeData', max_length=255)),
                ('year', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='Passwordreset',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('resetstring', models.CharField(db_column='resetString', max_length=64)),
                ('generated', models.DateTimeField()),
            ],
            options={
                'db_table': 'passwordReset',
            },
        ),
        migrations.CreateModel(
            name='Roominfo',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.IntegerField()),
                ('night', models.CharField(max_length=255)),
                ('numnights', models.IntegerField(db_column='numNights')),
                ('roomnumber', models.CharField(db_column='roomNumber', max_length=255)),
            ],
            options={
                'db_table': 'roomInfo',
            },
        ),
        migrations.CreateModel(
            name='Roommates',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.IntegerField()),
                ('wantstoroom', models.IntegerField(db_column='wantsToRoom')),
                ('likes', models.CharField(max_length=10000)),
                ('dislikes', models.CharField(max_length=10000)),
                ('nights', models.CharField(max_length=3)),
                ('smallroom', models.CharField(db_column='smallRoom', max_length=8)),
                ('atrium', models.CharField(max_length=8)),
                ('parties', models.IntegerField()),
                ('allergies', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'roommates',
            },
        ),
        migrations.AddField(
            model_name='tab',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerts',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roommates',
            unique_together={('email', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='roominfo',
            unique_together={('email', 'year', 'night')},
        ),
        migrations.AlterUniqueTogether(
            name='badges',
            unique_together={('email', 'year')},
        ),
    ]
