# Generated by Django 2.0.1 on 2018-01-28 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magsoft_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
