# Generated by Django 2.0.1 on 2018-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsoft_api', '0003_auto_20180303_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeExtras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('cost', models.SmallIntegerField()),
                ('has_shirt', models.BooleanField()),
                ('has_name', models.BooleanField()),
            ],
            options={
                'db_table': 'badgeExtras',
                'ordering': ['cost'],
            },
        ),
    ]
