# Generated by Django 2.0.1 on 2018-03-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsoft_api', '0004_badgeextras'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
