# Generated by Django 2.0.1 on 2018-03-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsoft_api', '0005_tab_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='badge_added',
            field=models.BooleanField(db_column='badgeAdded', default=False),
        ),
        migrations.AlterField(
            model_name='badges',
            name='badge_data',
            field=models.CharField(blank=True, db_column='badgeData', default='', max_length=255),
        ),
    ]
